# Switch between the existing custom-provider configuration and a local
# ChatGPT-account configuration. This script never prints or uploads secrets.
$ErrorActionPreference = "Continue"
$codexDir = Join-Path $env:USERPROFILE ".codex"
$activeConfig = Join-Path $codexDir "config.toml"
$apiProfile = Join-Path $codexDir "config.api.toml"
$chatgptProfile = Join-Path $codexDir "config.chatgpt.toml"

function Pause-Switcher {
    Write-Host ""
    [void](Read-Host "Press Enter to return to the menu")
}

function Require-ClosedClient {
    Write-Host "Close the Codex desktop app completely before continuing." -ForegroundColor Yellow
    $answer = Read-Host "Is the app closed? Type Y to continue"
    return $answer -match '^[Yy]$'
}

function Require-CodexCli {
    if (-not (Get-Command codex -ErrorAction SilentlyContinue)) {
        Write-Host "ERROR: Codex CLI was not found in PATH." -ForegroundColor Red
        return $false
    }
    return $true
}

function Create-ProfilesIfNeeded {
    if (-not (Test-Path -LiteralPath $activeConfig)) {
        throw "Cannot find $activeConfig"
    }

    if (-not (Test-Path -LiteralPath $apiProfile)) {
        Copy-Item -LiteralPath $activeConfig -Destination $apiProfile -Force
        Write-Host "Saved your current configuration as config.api.toml." -ForegroundColor Green
    }

    Build-ChatGPTProfile
}

function Build-ChatGPTProfile {
    # Rebuild every time from the complete API profile. A line-by-line state
    # machine is used instead of a multiline regular expression so custom
    # provider declarations and their table can never be removed separately.
    $output = New-Object System.Collections.Generic.List[string]
    $insideCustomProvider = $false

    foreach ($line in [System.IO.File]::ReadAllLines($apiProfile)) {
        $trimmed = $line.Trim()

        if ($trimmed -match '^model_provider\s*=') { continue }
        if ($trimmed -match '^model\s*=') { continue }
        if ($trimmed -match '^\[model_providers\]$') { continue }
        if ($trimmed -match '^\[model_providers\.custom\]$') {
            $insideCustomProvider = $true
            continue
        }
        if ($insideCustomProvider) {
            if ($trimmed -match '^\[') {
                $insideCustomProvider = $false
            } else {
                continue
            }
        }
        [void]$output.Add($line)
    }

    $header = @(
        '# ChatGPT-account profile generated by Codex Profile Switcher.',
        '# It intentionally has no custom provider, custom model, or API bearer token.',
        ''
    )
    $result = ($header + $output) -join [Environment]::NewLine
    if ($result -match '(?m)^\s*model_provider\s*=\s*"custom"' -or
        $result -match '(?m)^\s*\[model_providers\.custom\]') {
        throw "Safety check failed: the ChatGPT profile still contains the custom provider."
    }
    [System.IO.File]::WriteAllText($chatgptProfile, $result + [Environment]::NewLine)
    Write-Host "Rebuilt config.chatgpt.toml without the CPA custom provider." -ForegroundColor Green
}

function Backup-ActiveConfig {
    $stamp = Get-Date -Format "yyyyMMdd-HHmmss"
    $backup = Join-Path $codexDir "config.before-switch-$stamp.toml"
    Copy-Item -LiteralPath $activeConfig -Destination $backup -Force
}

function Activate-ChatGPT {
    if (-not (Require-ClosedClient)) { return }
    try {
        Create-ProfilesIfNeeded
        Backup-ActiveConfig
        Copy-Item -LiteralPath $chatgptProfile -Destination $activeConfig -Force
        Write-Host "Activated the ChatGPT configuration profile." -ForegroundColor Green

        if (-not (Require-CodexCli)) { return }
        & cmd.exe /d /c "codex logout >nul 2>&1"
        Write-Host "Opening the ChatGPT login flow..." -ForegroundColor Cyan
        & cmd.exe /d /c "codex login"

        if ($LASTEXITCODE -eq 0) {
            Write-Host "SUCCESS: ChatGPT login completed." -ForegroundColor Green
            & cmd.exe /d /c "codex login status"
        } else {
            Write-Host "Login was not completed. The ChatGPT config is still active." -ForegroundColor Yellow
        }

        $userKey = [Environment]::GetEnvironmentVariable("OPENAI_API_KEY", "User")
        $machineKey = [Environment]::GetEnvironmentVariable("OPENAI_API_KEY", "Machine")
        if ($userKey -or $machineKey) {
            Write-Host "WARNING: OPENAI_API_KEY is still set in Windows environment variables." -ForegroundColor Yellow
            Write-Host "If the desktop app still shows API login after restarting, remove that variable in Windows Environment Variables, then restart the app."
        }
    }
    catch {
        Write-Host "ERROR: $($_.Exception.Message)" -ForegroundColor Red
    }
}

function Activate-ApiProvider {
    if (-not (Require-ClosedClient)) { return }
    try {
        Create-ProfilesIfNeeded
        Backup-ActiveConfig
        Copy-Item -LiteralPath $apiProfile -Destination $activeConfig -Force
        Write-Host "SUCCESS: Restored your custom API/CPA configuration." -ForegroundColor Green
        Write-Host "No API key is requested: the restored configuration uses its existing bearer token."
    }
    catch {
        Write-Host "ERROR: $($_.Exception.Message)" -ForegroundColor Red
    }
}

function Show-Status {
    Write-Host "Active configuration: $activeConfig"
    if (Test-Path -LiteralPath $activeConfig) {
        $content = [System.IO.File]::ReadAllText($activeConfig)
        if ($content -match '(?m)^model_provider\s*=\s*"custom"') {
            Write-Host "Provider mode: custom API/CPA" -ForegroundColor Yellow
        } else {
            Write-Host "Provider mode: OpenAI / ChatGPT default" -ForegroundColor Green
        }
    }
    if (Require-CodexCli) { & cmd.exe /d /c "codex login status" }
}

while ($true) {
    Clear-Host
    Write-Host "=============================================="
    Write-Host "      Codex Configuration Profile Switcher"
    Write-Host "=============================================="
    Write-Host "1. Use my Google / ChatGPT account"
    Write-Host "2. Use my custom API / CPA provider"
    Write-Host "3. Show active profile and login status"
    Write-Host "4. Exit"
    $choice = Read-Host "Select 1-4"
    switch ($choice) {
        "1" { Activate-ChatGPT; Pause-Switcher }
        "2" { Activate-ApiProvider; Pause-Switcher }
        "3" { Show-Status; Pause-Switcher }
        "4" { exit 0 }
        default { Write-Host "Please enter 1, 2, 3, or 4."; Start-Sleep -Seconds 1 }
    }
}
